---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load the FAS litters data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## 'select'

Choose some columns and not others

```{r}
select(litters_df, group, litter_number)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```


Removing certain column
```{r}
select(litters_df, -litter_number)
```


Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```


Select helpers

```{r}
select(litters_df, starts_with("gd"))
```


move the chosen column to the first column and keep everything else, both of the following work
```{r}
select(litters_df, litter_number, everything())
```


```{r}
relocate(litters_df, litter_number)
```


##   'filter'

```{r}
filter(litters_df, gd0_weight < 22)
```


```{r}
filter(litters_df, gd0_weight >= 22)
```


```{r}
filter(litters_df, gd_of_birth == 20)
```


```{r}
filter(litters_df, !(gd_of_birth == 20))
filter(litters_df, gd_of_birth != 20)
```


```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```


```{r}
filter(litters_df, group == "Con7")
```


Filter out all the rows that contain "Mod8","Con7" in the their group
```{r}
filter(litters_df, group %in% c("Mod8","Con7"))
```



## 'mutate'


create a new variable and modify an existing variable 

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
  )
```




